# 🔧 pyproject.toml: Formatters, Linters, Type Checker
[tool.black]
line-length = 88
include = '\.pyi?$'

[tool.ruff]
line-length = 88
exclude = [".venv", "build", "dist"]
select = ["E", "F", "I", "C90"]

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
strict_optional = true

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
